num1=input('Enter a number: ')
num2=input('Enter second number: ')
print(num1,'+',num2,'=', int(num1)+int(num2) )
print(num1,'-',num2,'=', int(num1)-int(num2) )
print(num1,'*',num2,'=', int(num1)*int(num2) )
print(num1,'/',num2,'=', float(num1)/float(num2) )
print(num1,'%',num2,'=', int(num1)%int(num2) )